### PR TITLE
Update railties dependencies to >= 3.2.9

### PR DESCRIPTION
**Pull request by pedrosmmoreira**
Update railties dependencies to enable gem use with apps that depend on Railties 4.0.0

### CODE REVIEW

**Comment by blackxored** [comment]
Are you sure that such a loose dependency wouldn't break this gem on the future? How's rails 4 have you tried with it?

```
—
```

**Comment by pedrosmmoreira** [comment]
I'm using it with Rails 4 in production, without any problems so far. I've left the dependency loose to try and keep it as compatible as possible.

**Comment by blackxored** [comment]
Ok good ill do some testing and merge tomorrow. Thanks a lot for your contrib

```
—
```

**Comment by pedrosmmoreira** [comment]
No problem, glad to help :)

**Comment by anilmuppalla** [comment]
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    fontello-rails (>= 0) ruby depends on
      railties (~> 3.2.9) ruby

```
devise (>= 0) ruby depends on
  railties (4.0.0)
```

How do i fix this? i am trying to upgrade to rails 4

**Comment by blackxored** [comment]
It's on the works. 

```
—
```

**Pull request closed without merging**
